version: "3.8"

services:
  backend:
    container_name: backend
    init: true
    build: ../
    env_file:
      - ../.env
    # Override the value of host.
    environment:
      - DB_HOST=db
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_1234
      POSTGRES_DB: db_prj
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
